-- export h2 dataset to mysql
CREATE TABLE ORDERS (
	ID BIGINT NOT NULL,
	USER_ID INTEGER,
	PRODUCT_ID INTEGER,
	SUBTOTAL DOUBLE,
	TAX DOUBLE,
	TOTAL DOUBLE,
	DISCOUNT DOUBLE,
	CREATED_AT TIMESTAMP,
	QUANTITY INTEGER
);


CREATE TABLE PEOPLE (
	ID BIGINT NOT NULL,
	ADDRESS VARCHAR(255),
	EMAIL VARCHAR(255),
	PASSWORD VARCHAR(255),
	NAME VARCHAR(255),
	CITY VARCHAR(255),
	LONGITUDE DOUBLE,
	STATE CHAR(2),
	SOURCE VARCHAR(255),
	BIRTH_DATE VARCHAR(255),
	ZIP CHAR(5),
	LATITUDE DOUBLE,
	CREATED_AT TIMESTAMP
);


CREATE TABLE PRODUCTS (
	ID BIGINT NOT NULL,
	EAN CHAR(13),
	TITLE VARCHAR(255),
	CATEGORY VARCHAR(255),
	VENDOR VARCHAR(255),
	PRICE DOUBLE,
	RATING DOUBLE,
	CREATED_AT TIMESTAMP
);

CREATE TABLE REVIEWS (
	ID BIGINT NOT NULL,
	PRODUCT_ID INTEGER,
	REVIEWER VARCHAR(255),
	RATING SMALLINT,
	BODY TEXT,
	CREATED_AT TIMESTAMP
);
